ali-sdk/ali-oss

- .jshintignore
- .jshintrc
- .npmignore
- .travis.yml
- Makefile
- README.md
- callback_example.js
- example.js
- lib/client.js
- package.json
- test/client.test.js
Fixes https://github.com/cnpm/oss-cnpm/issues/10
> feat: support signature url

- .travis.yml
- lib/client.js
- lib/object.js
- test/object.test.js
> feat: add getStream*() api

- lib/client.js
- lib/image.js
- lib/object.js
- test/image.test.js
`ImageClient.prototype.putStyle` and `ImageClient.prototype.deleteStyle` not work
> Image service API

- README.md
太简单了，直接 diff 下吧，ps：阿里云提供英文版的文档了
> fix some spelling mistakes

- lib/client.js
> feat(createRequest): expose create request method

- README.md
- lib/client.js
> add endpoint into readme

- README.md
- lib/client.js
- test/bucket.test.js
- test/config.js
- test/multipart.test.js
另外，travis CI的运行环境中`/dev/random`不能用，改成`/dev/urandom`
> Fix IE10 compatibility and refine test

- .autod.conf.js
- package.json
add pre-release and post-release hook
> deps: update dependencies

- README.md
- lib/client.js
- test/client.test.js
`x-oss-user-agent`是因为浏览器中不允许设置`User-Agent`
> add user-agent in header

- .autod.conf.js
- package.json
- publish.js
> add script to publish dist/ to cdn after each release

- lib/client.js
- package.json
- test/client.test.js
> Browser user agent

- package.json
> stop check leaks in test

- browser-build.js
- package.json
- shims/crypto.js
From: 
```
-rw-r--r--   1 rockuw  staff   1.1M Apr 12 17:03 aliyun-oss-sdk.min.js
-rw-r--r--   1 rockuw  staff   1.7M Apr 12 17:03 aliyun-oss-sdk.js
```
to:
```
-rw-r--r--   1 rockuw  staff   852K Apr 12 17:03 aliyun-oss-sdk.js
-rw-r--r--   1 rockuw  staff   358K Apr 12 17:03 aliyun-oss-sdk.min.js
```
> Rework browser build to reduce dist size

- lib/multipart.js
- lib/object.js
- test/config.js
- test/multipart.test.js
- test/object.test.js
- test/utils.js
> Correctly parse Put/MultipartUpload response when using upload callback

- .gitignore
- README.md
> fix readme spelling Mistakes

- .travis.yml
- lib/client.js
> fix: support node 6

- lib/multipart.js
> Fix memory leak in multipart

- lib/client.js
- lib/multipart.js
- package.json
- test/client.test.js
- test/multipart.test.js
yield generator[]并发的方式在IE10环境中兼容性有些问题，暂且针对IE10环境使用原有的非并发处理。
本次引入了两个包：
1. [bowser]负责检查浏览器名称和版本
2. [sinon]负责在自动测试里做mock处理
> fix multipartUpload can not work with IE10 bug

- lib/multipart.js
1. 修复注释错误
2. 在readFileAndPush中追加null object 判断
> fix comment typo and add object check to avoid call properties of null object

- lib/client.js
- test/client.test.js
> support VPC region #181

- .travis.yml
- lib/client.js
- package.json
- test/multipart.test.js
- test/object.test.js
and skip callbackurl test cases
> test: set default platform on user-agent

- README.md
- lib/client.js
- lib/object.js
- test/fixtures/foo.js
- test/object.test.js
Ref: https://help.aliyun.com/document_detail/31981.html
> feat: support oss.append 

- lib/client.js
> fix issue #288: startsWith not support by ie11

- README.md
- lib/browser/multipart.js
- lib/browser/version.js
- lib/multipart.js
- test/browser.tests.js
- test/multipart.test.js
- test/wrapper.test.js
1.add x-oss-request-id in multipart about init, upload part and complete
> 分片上传增加init upload part,complete3个情况的 requestId

- package.json
fix safari blob fail case, use arrayBuffer to send
#286 #337
> fix safari blob fail case

- lib/browser/client.js
- test/browser.tests.js
fix: RequestTimeTooSkewed  set with client options
> fix: RequestTimeTooSkewed

- README.md
add timeout doc about multipart
> add timeout doc about multipart

- lib/browser/client.js
add local protocol check for web
> feat: add local protocol check for web

- lib/browser/multipart.js
- lib/multipart.js
fix multipartUpload small file upload by callback data
Closes #319 and #357
> fix: multipartUpload small file upload by callback data

- lib/browser/client.js
- lib/client.js
- test/browser.tests.js
- test/client.test.js
fix: userAgent with alpha and beta
closes #361 #368
> fix: userAgent with alpha and beta

- README.md
add options doc and multipart options-progress doc
> feat: add options doc and multipart options-progress doc

- example/index.js
- example/webpack.prod.js
- package.json
1.add example with build in react
> feat: example with build in react

- lib/common/thunkpool.js
> refactor(thunkpool): job function out of loops

- README.md
- lib/browser/managed_upload.js
- lib/browser/object.js
- lib/common/callback.js
- lib/common/multipart-copy.js
- lib/common/multipart.js
- lib/managed_upload.js
- lib/object.js
- test/browser.tests.js
- test/callback.test.js
- test/config.js
- test/const.js
- test/object.test.js
1.support callback options for put and multipartUpload
> feat: support callback options for put and multipartUpload

- package.json
> fix: add any-promise dependencies

- shims/xhr.js
fix: fix bug about value of requestTimeout!
> fix: fix bug about value of requestTimeout!

- example/index.js
- lib/browser.js
feat: expose sdk version with OSS
> feat: expose sdk version with OSS

- .gitignore
feat: add ignore about test/node/.tmp  test/browser/.tmp
> feat: add ignore about test

- lib/browser/managed_upload.js
- lib/common/multipart.js
- test/node/callback.test.js
fix: multipartUpload InvalidPartOrderError by doneParts repeat
Close #404
> fix(Browser): multipartUpload InvalidPartOrderError by doneParts repeat

- karma.conf.js
- lib/browser/client.js
- lib/client.js
- lib/common/signUtils.js
- package.json
- task/browser-test-build.js
- test/browser/browser.test.js
1.signUtils header sort err fix
2.add safari browser test config
> fix: signUtils header sort err fix

- README.md
> feat: modify readme.md add err code

- .eslintrc.js
- lib/browser/managed_upload.js
- lib/browser/object.js
- lib/common/callback.js
- lib/common/multipart.js
- lib/managed_upload.js
- lib/object.js
- publish.js
- test/browser/browser.test.js
- test/node/callback.test.js
- test/node/utils.js
Fix: multipartUpload callback resumble parse error
Close #420
> Fix: multipartUpload callback resumble parse error

- example/index.html
- example/index.js
- lib/common/signUtils.js
- task/browser-test-build.js
- test/browser/browser.test.js
- test/node/object.test.js
fix signatureUrl with content-type and content-md5
> fix signatureUrl with content-type and content-md5

- example/index.html
- example/index.js
test: add sample about cname's usage
> test: add sample about cname's usage

- package.json
- publish-check.js
- publish-npm-check.js
- publish.js
> feat: publish CDN check script

- README.md
- lib/browser/bucket.js
- lib/browser/object.js
- lib/bucket.js
- lib/object.js
- test/node/bucket.test.js
- test/node/object.test.js
feat:add restore object api
feat:support to create archive bucket
test:add restore object test case
docs : add restore object docs
> feat: restore object api and support to  create archvie bucket

- README.md
- lib/browser/object.js
- lib/object.js
- test/node/bucket.test.js
- test/node/object.test.js
feat: add generateObjectUrl api 
test: add generateObjectUrl test case and modfiy putBucket test case 
docs:add generateObjectUrl docs
Close #340 #267
> add generateObjectUrl api

- package.json
> chore: add test code coverage

- lib/common/signUtils.js
- test/browser/browser.test.js
- test/node/object.test.js
fix: fix signatureUrl With response settings
Close #464
> fix: fix signatureUrl With response settings

- lib/browser/client.js
- lib/client.js
> fix: rtmp generate url

- shims/xhr.js
if browser support AbortController api , stream-http will throw timeout error warn
> fix(browser): stream-http timeout error

- README.md
- lib/bucket.js
- test/node/bucket.test.js
1.  add getBucketLoaction and getBucketInfo
2. add getBucketLoaction and getBucketInfo test case 
3. add getBucketLoaction and getBucketInfo docs
> Add getBucketLocation and getBucketInfo

- shims/xhr.js
fix: 
repair timeout excepiton
remove capability.abortController judge code
> fix: repair timeout excepiton

- example/config/webpack.dev.conf.js
modify config to support ip visit about example
add host:'0.0.0.0' in the DevServer Config
> fix: modify config to support ip visit about example

- test/browser/browser.test.js
fix: clean the objects in bucket when running test case in browser
> Clean browser test bucket

- lib/browser/client.js
- lib/client.js
fix: remove replace %20 to '+'
> fix: remove replace %20 to '+'

- .gitignore
- dist/aliyun-oss-sdk.js
- lib/browser/client.js
- lib/bucket.js
- lib/client.js
- test/node/bucket.test.js
- test/node/object.test.js
fix:
remove comments,
modify .gitignore
add case for url encode
> chore: remove comments, modify .gitignore and add case for url encode

- example/package.json
- example/src/main.js
> chore: repair example

- .travis.yml
- lib/client.js
- package.json
- test/node/object.test.js
backport from https://github.com/ali-sdk/ali-oss/pull/503
> fix: should consume the response stream on error

- example/script.js
- example/server/app.js
> Fix example window32

- .github/ISSUE_TEMPLATE.md
- README.md
- UPGRADING.md
> docs:README.md and upgrade.md

- example/src/main.js
> fix: eslint example

- .eslintrc.js
- example/config/webpack.dev.conf.js
- lib/browser/object.js
- test/node/utils.test.js
> chore: eslint

- package.json
latest `urllib` has many bugs fixed: https://github.com/node-modules/urllib/blob/master/History.md
> Bump version of urllib

- README.md
- lib/cluster.js
set options.masterOnly = true to enable the feature
> feat: only read from master

- README.md
> append markdown

- README.md
> docs: update putMeta doc

- browser-build.js
> FIX: 修复乱码问题

- lib/bucket.js
- lib/common/utils/checkBucketname.js
- test/node/bucket.test.js
> Fix bucket ssrf

- browser-build.js
document is not available for web worker while location is available
> document is not available for web worker

- README.md
- lib/browser/client.js
FIX: browser.js add console.warn
> FIX: browser.js add console.warn

- README.md
- lib/browser/object.js
- lib/client.js
- lib/common/object/getObjectMeta.js
- lib/common/object/getSymlink.js
- lib/common/object/index.js
- lib/common/object/putSymlink.js
- lib/object.js
- test/browser/browser.test.js
- test/node/object.test.js
feat: add putSymlink and getSymlink
fix: put and putStream name replace '/' at begin
feat: add getObjectMeta
> feat: symlink

- lib/browser/client.js
- lib/browser/object.js
- test/browser/browser.test.js
- test/node/object.test.js
fix: put stream content empty when date is skew
Close #604
> fix: put stream content empty when date is skew

- README.md
- test/browser/browser.test.js
- test/node/object.test.js
test:  put object with same name
docs: update headers link
> test:  put object with same name

- lib/browser/object.js
> fix: proto.put TypeError text

- README.md
Update description information of `getBucketVersions`
>  chore: update README.md

- lib/browser/managed-upload.js
to process small file in browser
> fix: use put insteadof putStream when calling multipartUpload

- lib/client.js
- test/browser/browser.test.js
- test/node/bukcet_worm.test.js
- test/node/multipart.test.js
- test/node/multiversion.test.js
https://github.com/ali-sdk/ali-oss/pull/726
> fix: merge conflict #726

- README.md
- lib/browser/object.js
- lib/object.js
- package.json
- test/browser/browser.test.js
- test/node/object.test.js
The continuation-token params in listV2 should be a part of subres.
listV2中的continuation-token参数应该是subres的一部分.
> fix: the continuation-token params in listV2

- README.md
有些链接已经更换，但是文档中的 URL 没有更新。
另外，在 #bb565c202abbea2b329d4c03b0eddaed9ece9766 的 README.md 第 4429 行的链接 <https://help.aliyun.com/document_detail/oss/practice/ram_guide.html> 暂时没有找到对应的链接，需要你们补充一下。
> docs: update outdated links.

- lib/client.js
- lib/common/utils/createRequest.js
- lib/common/utils/createRequest.ts
> fix: remove node enviroment x-oss-user-agent

- .github/workflows/codeCov.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/node_test.yml
- .github/workflows/snyk.yml
> feat: add develop gitaction

- lib/object.js
> fix listV2 params error

- lib/common/signUtils.js
> fix: to append method signatureNotMath

- lib/browser/client.js
- test/browser/browser.test.js
add multipartUploadCopy method
> add multipartUploadCopy method

- test/browser/browser.test.js
- test/node/object.test.js
> chore(test case): fix test case

- test/node/utils/retry.test.js
> chore(test): test case optimized

- lib/browser/object.js
- lib/object.js
- test/browser/browser.test.js
- test/node/object.test.js
fix list() and listV2() params and test case
> fix: list() and listV2() params and test case

- README.md
- lib/client.js
> chore: adjust download  request hints

- test/browser/browser.test.js
feat: add asyncSignatureUrl browser test case
> chore(7.x): add asyncSignatureUrl browser test case

- .github/workflows/master_node_test.yml
- lib/common/object/head.js
- lib/common/utils/checkEnv.d.ts
- lib/common/utils/checkEnv.js
- lib/common/utils/checkEnv.ts
- add head method warning
- adjust PR githubCi
> chore: some optimized

- browser-build.js
Adjustment of the packing method
> fix: isolation of variables to prevent contamination

- .github/workflows/master_node_test.yml
- package-lock.json
- package.json
> fix(6.x): lock dependencies

- .github/workflows/master_node_test.yml
- .github/workflows/schedule.yml
- test/node/cleanAllBucket.js
chore: add schedule delete 7day ago bucket
> chore(6.x): add schedule delete 7day ago bucket

- .github/workflows/schedule.yml
- test/node/cleanAllBucket.js
> chore: schedule CI/CD

- README.md
- package.json
- test/node/object.test.js
chore: remove mz-modules and fix doc
> chore: remove mz-modules and fix doc

- package.json
> chore: remove mz-module

- README.md
> chore: doc adjustments

- test/node/cleanAllBucket.js
> chore: utils optimized

- CHANGELOG.md
- package.json
* chore(release): 6.18.1
* chore: release 6.18.1
---------
> chore: release 6.18.1 (#1249)

- lib/browser/client.js
- lib/client.js
- lib/common/object/signatureUrlV4.js
- lib/common/signUtils.js
- test/browser/browser.test.js
- test/node/multipart.test.js
- test/node/rtmp.test.js
fix requestError return null and signatureUrlV4 run in Node 8.x
> fix: fix requestError return null and signatureV4 run in Node 8.x

- README.md
- lib/browser/object.js
- lib/common/object/getBucketVersions.js
- lib/common/utils/parseRestoreInfo.d.ts
- lib/common/utils/parseRestoreInfo.js
- lib/common/utils/parseRestoreInfo.ts
- lib/object.js
- package-lock.json
- package.json
- test/browser/browser.test.js
- test/node/multiversion.test.js
- test/node/object.test.js
list object functions support return restore info
> feat: list object functions support return restore info
