browser.js, lib/client.js, lib/multipart.js, lib/object.js, test/client.test.js, test/multipart.test.js, test/object.test.js
现在:
- `put`接口可以支持String(file path)/Buffer/ReadableStream
- `putStream`接口可以支持'chunked'（默认）和非'chunked'（通过指定contentLength）
```js
var stream = fs.createReadStream(__filanem);
var size = fs.statSync(__filename).size;
yield store.putStream(name, stream, {contentLength: size});
```
=> Fix ip endpoint

README.md, lib/client.js, lib/wrapper.js, test/multipart.test.js, test/utils.js, test/wrapper.test.js
很多用户还是习惯用callback的方式，返回promise可以让用户不用`co`也能用起来：
```js
var OSS = require('ali-oss').Wrapper;
var client = new OSS({
endpoint: 'http://oss-test.aliyun-inc.com/ ',
accessKeyId: 'xxxx',
accessKeySecret: 'yyyy',
bucket: 'bucket'
});
client.put('hello', new Buffer('world')).then(function (val) {
console.log('result: %j', val);
}).catch (function (err) {
console.log('error: %j', err);
});
```
=> Add a wrapper to return Promise

lib/cluster.js, test/cluster.test.js
add options.ignoreStatusFile to ignore put check status file on cluster mode for some reasons, eg: read only account.
=> feature: add options.ignoreStatusFile to skip put status check file

lib/client.js, lib/wrapper.js, package.json
1. `return isGenerator(constructor.prototype)` 这句话似乎是不对的，要换成`return isGenerator(obj.prototype)`
2. IE10的`toUTCString()`的日期不是两位数
=> Fix isGeneratorFunction and Date format problems in IE10

README.md
I got a surprise when write `yield get(somepath, null, options)`
=> doc: param "file" of *get method is optional

lib/object.js, test/object.test.js
fix #139
1. fix the copy object api bug which can not use non-English source object name
2. add a test case to test copy api with non-English source object name
=> fix the copy object api bug which can not use non-English source object name

package.json
main is **lib/client.js**, but it requires **bowser**, so **bowser** should be in **dependencies**
=> :bug: fix bowser dependency

lib/browser/client.js, package.json, test/browser.tests.js
When the client's date time is skew, the request will calibration time and retry, same as IOS and Android
=> process the client's local time is skew

README.md, lib/browser/multipart.js, lib/multipart.js, test/browser.tests.js, test/multipart.test.js
fix: the multipartUpload return value has same object
when file size is small then minPartSize, the multipartUpload methods also return ‘bucket’、‘name’、‘etag’
Closes #282
=> fix: the multipartUpload return value has same structure

lib/browser/client.js, lib/client.js, lib/common/signUtils.js
refactor: authorization refactor
=> refactor: authorization refactor

browser-build.js, package.json, shims/crypto.js, shims/crypto/crypto.js, shims/crypto/helpers.js, shims/crypto/md5.js, shims/crypto/sha.js, shims/crypto/sha256.js
fix: crypto about browser bug
Close #386
=> fix: crypto about browser bug

README.md, lib/browser/object.js, lib/common/signUtils.js, lib/object.js, test/node/object.test.js
feat: signatureUrl refactor and support callback,Close #135
=> feat: signatureUrl refactor and support callback

README.md, example/index.js
add example base64 to blob and doc
=> feat: example base64 to blob and doc

README.md
add browser cdn Introduce instructions
=> docs: browser cdn Introduce instructions

.travis.yml, lib/client.js, lib/object.js, package.json, test/browser.tests.js, test/callback.test.js, test/object.test.js, test/rtmp.test.js, test/sts.test.js, test/utils.js
backport from https://github.com/ali-sdk/ali-oss/pull/503
=> fix: should consume the response stream on error

lib/cluster.js, test/node/cluster.test.js
set options.masterOnly = true to enable the feature
pick from https://github.com/ali-sdk/ali-oss/pull/622
=> feat: only read from master

lib/browser/managed-upload.js, lib/browser/object.js
浏览器环境下 file 不可能是 string，所以 _statFile() 方法时无用的。
=> feat: remove unused proto._statFile

.prettierrc, package.json, shims/is-type-of.js
`aliyun-oss-sdk.min.js` 体积从 `451K` 减小到 `397K`
=> feat: browser端,将 is-type-of 包处理为本地 shim

lib/common/bucket/putBucketLifecycle.js, test/node/bucket.test.js
Using an empty prefix string `""` should be supported in bucket life-cycle: `{prefix: ""}` is supported for rule that applied to whole bucket.
For example, when using the **Whole Bucket/配置到整个 Bucket** option:
You get the following rule with `getBucketLifeCycle`:
```console
> aliApi.getBucketLifecycle(bucket).then(console.log);
Promise { <pending> }
> {
rules: [
{
prefix: '', // <-- empty prefix here
status: 'Enabled',
abortMultipartUpload: [Object],
id: '******'
}
],
res: {
status: 200,
...
```
=> fix: Support empty prefix in putBucketLifecycle

README.md, lib/browser/managed-upload.js, lib/managed-upload.js, test/browser/browser.test.js, test/node/multipart.test.js
Allows `.multipartUpload()` to take a [Node.JS Buffer](https://nodejs.org/api/buffer.html#buffer_class_buffer) as a parameter. 
Before, `.multipartUpload` only supported parameter:
- file {String|File(only support Browser)|Blob(only support Browser)} file path or HTML5 Web File or web Blob
Now, `.multipartUpload` supports parameter:
- file {String|File(only support Browser)|Blob(only support Browser)|**Buffer**} file path or HTML5 Web File or web Blob or **content buffer**
=> feat: multipartUpload support Node.JS Buffer

README.md, test/browser/browser.test.js, test/node/object.test.js
revise `start-after` and add test case
修订`start-after`文档 和 增加对应测试用例
=> docs: revise `start-after` in listV2

lib/common/utils/deepCopy.js, lib/common/utils/deepCopy.ts, test/node/utils/deepCopy.test.js
`deepCopy()` does not work when copying an object with a large Buffer (see test case).
This causes issues when using `multipartUpload()` when `file` is a very big `Buffer` (~1GB) and with the `checkpoint` option, since in [completeMultipartUpload](https://github.com/ali-sdk/ali-oss/blob/afaf0ed924ddbbbdaf20eb9c299d44e964cc704c/lib/common/multipart.js#L186) we `deepCopy` all the options.
Example:
```js
const file = Buffer.alloc(Math.pow(2, 30) - 1); // ~ 1GB
const savedCheckpoint = {file, ...} // made from multipartUpload#progress
// throws RangeError in utils/deepCopy, when copying options.checkpoint.file
multipartUpload("name", file, {checkpoint: savedCheckpoint});
```
Copying all `Buffer` in `deepCopy()` using `Buffer.from` seems to fix this issue.
=> fix(node): deepCopy not working for large Buffers

package.json
per unofficial "spec" https://github.com/defunctzombie/package-browser-field-spec
local files should be referenced with `./`. this allows for distinction between package and local file re-mapping.
changed `"main"` as well just for consistency. doesn't really matter there.
=> fix: spec compatible "browser" mapping

karma.conf.js, test/browser/browser-utils.js, test/browser/browser.test.js
=> fix(test): test case optimized

lib/common/parallel.js
用`esbuild`发现这段代码，跟`{}`对比每次都返回false，因为用得是`||`，所以直接删除就行
=> fix: remove Invalid Comparison

README.md, lib/browser/managed-upload.js, lib/browser/object.js, lib/common/bucket/putBucketLifecycle.js, lib/common/multipart.js, lib/common/signUtils.js, lib/managed-upload.js, lib/object.js, task/browser-test-build.js, test/browser/browser.test.js, test/config.js, test/node/bucket.test.js, test/node/callback.test.js, test/node/multipart.test.js, test/node/multiversion.test.js, test/node/object.test.js, test/node/rtmp.test.js
=> fix: queries sort in signatureUrl and add cases
